Repository grammyjs/grammY, pull requests merged in 2021-11, with the labels that each got.

#55 Automatically pick correct agent based on protocol
  src/core/client.ts
  src/platform.deno.ts
  src/platform.node.ts
Labels: enhancement

#94 Allow URLs as strings for InputFile
  src/core/payload.ts
  src/platform.deno.ts
  src/platform.node.ts
Labels: enhancement, needs investigation

#77 Rework InputFiles
  src/core/payload.ts
  src/platform.deno.ts
  src/platform.node.ts
  test/bot.test.ts
  test/filter.test.ts
Labels: fix

#61 Rework framework adapters, and add new ones
  package.json
  src/convenience/frameworks.deno.ts
  src/convenience/frameworks.node.ts
  src/convenience/webhook.ts
Labels: enhancement

#91 Add `Deno.serveHttp` adapter for `webhookCallback`
  src/convenience/frameworks.deno.ts
Labels: enhancement

#111 ES6 bundling
  .github/workflows/cdn.yml
  .github/workflows/deno.yml
  bundling/.gitignore
  bundling/bundle-es6.ts
  bundling/netlify.toml
Labels: enhancement, help wanted
